### ISSUE TITLE
fast single-page-app filtering for search results

### ISSUE THREAD

**Issue by micahstubbs** [enjalot/blockbuilder-search#13]
something like this perhaps

![spa-filter-480px](https://cloud.githubusercontent.com/assets/2119400/26606512/0e435ea8-4547-11e7-8a10-7e33a4f8faa3.gif)

<img width="1920" alt="screen shot 2017-05-30 at 2 42 33 pm" src="https://cloud.githubusercontent.com/assets/2119400/26606446/cdbe6f62-4546-11e7-8e83-e92d78402165.png">

from file in this React tutorial repo

https://github.com/micahstubbs/complete-intro-to-react/blob/db693085493584ffc56a9da50d0ddaf7565090d2/js/Search.jsx

**Comment by hydrosquall** [comment]
Hi @micahstubbs - I am interested in picking this up if there isn't already something in progress :).

**Comment by micahstubbs** [comment]
@hydrosquall thanks for commenting.  would be happy to have contributions generally.  that said, I'm making changes in https://github.com/enjalot/blockbuilder-search/pull/72#discussion_r224353971

that call the backend a lot more often.  after some conversations other places, the consensus that we got to is that backend calls are usually cheap/fast, and that there's real benefit to see a complete set of results from the elasticsearch index

**Comment by micahstubbs** [comment]
so yea, I'll go ahead and close this one, but @hydrosquall do let me know if you'd like any more-synchronous help getting a blockbuilder + blockbuilder-search dev environment setup

we definitely welcome contributions and ideas in new issues 😄
