### ISSUE TITLE
Infinite Scroll when `thumb=true`

### ISSUE THREAD

**Issue by curran** [enjalot/blockbuilder-search#77]
The infinite scroll appears not to function correctly when `thumb=true`.

Example test case:

https://blockbuilder.org/search?d3version=v5&thumb=true

Expected behavior: infinite scroll kicks in and fetches more results if you filter by thumbnails.

Actual behavior: when you filter by thumbnails, infinite scroll does not kick in.

Workaround: Use browser zoom to make the vertical scrollbar appear, then scroll to the bottom to trigger infinite scroll.

Possible solution 1: Leverage the thumbnail filter event (in addition to the scroll events) for triggering fetching of more results (hard).

Possible solution 2: Bring back the "Load more" button, for this case where the results are not automatically fetched (easy).

**Comment by curran** [comment]
Oops nevermind!! It does appear to be working correctly. I tested with v4 and everything works fine. I suppose there are just not enough v5 examples to populate the next page of results.

**Comment by micahstubbs** [comment]
@curran I think that's right.  one page === 512 results right now.  when I checked, there were only 137 v5 results.

**Comment by curran** [comment]
Indeed. Sorry for the false alarm!
