### ISSUE TITLE
show block-camera thumbnail if none is found

### ISSUE THREAD

**Issue by micahstubbs** [enjalot/blockbuilder-search#79]
show block-camera thumbnail if none is found

https://github.com/bayd3/block-camera

**Comment by micahstubbs** [comment]
ok, it looks like it is working 

dev on the left | prod on the right
![screen shot 2018-10-30 at 12 18 08 am](https://user-images.githubusercontent.com/2119400/47702184-63969800-dbd9-11e8-8a22-fba5542e74ac.png)

**Comment by curran** [comment]
Latent knowledge being unearthed! It's like an archaeology expedition. Great work @micahstubbs !

**Comment by micahstubbs** [comment]
fixed in https://github.com/enjalot/blockbuilder-search/pull/80
